### ISSUE TITLE
Forum Posts keep getting "Bumped" how do we stop that?

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#684] opened 2021-05-07 14:22 UTC
![Screen Shot 2021-05-07 at 7 21 04 AM](https://user-images.githubusercontent.com/14945613/117463822-5d26cb00-af50-11eb-8c14-a14ae2ca99d2.png)

**Comment by tamarandom** [comment] 2021-05-25 10:16
Dupe of #693

**Closed by tamarandom** 2021-05-25 10:16 UTC
Labels: Communications WG, Community, Content & Distribution, Medium, Next sprint?, Parameters WG, documentation, good first issue, help wanted
