### ISSUE TITLE
Improvements to the forum.

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#315] opened 2021-01-12 12:44 UTC
## 📋We want to see the incorporation of two things on the forum:

- Welcoming automated messages for new people / or different uses that having this system may bring.
- Post count system, that not necessarily is post count, it could be read time too, but that's linked to the praise system. 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ]

**Comment by tamarandom** [comment] 2021-01-14 10:32
Hey @eduardovegap! Thanks for adding this. I'm removing @iviangita as both the items descirbed are outside the scope of what she is working on. @freedumbs00 is the man for Forum and I'll assign it to him. @freedumbs00 you might already be tracking this in another issue and feel free to close this one if you are.

**Comment by freedumbs00** [comment] 2021-01-14 11:57
Thanks @tamarandom .  Im on it

**Comment by freedumbs00** [comment] 2021-01-14 16:50
@tamarandom  Can I actually transfer this issue to https://github.com/TECommons/coordination/issues/317. 

That's an overall and bigger one I would also note that is a WIP with @markoprljic  and we move it to next sprint and not sprint backlog?

**Comment by tamarandom** [comment] 2021-01-14 22:42
@freedumbs00 My initial reaction is that #317 is visual design and what @eduardovegap is describing here is (1) a feature to improve the user journey and (2) a consideration about how to dish praise based on forum participation. That latter part is covered by #37 (experimenting with SourceCred) and #272 (a higher level holistic overview of Praise). As for the user journey improvement.... I'd ask @jessicazartler and @liviade1 ;)

**Comment by freedumbs00** [comment] 2021-01-14 22:54
Okay....  I guess..  Thanks. Lol

**Comment by markoprljic** [comment] 2021-01-15 12:29
Maybe this could all be grouped into an Epic?

**Comment by tamarandom** [comment] 2021-01-17 08:28
@markoprljic Yes! Creating an Epic to add all the issues related to design or structure of the forum is the right idea. Quick search : #315, #317, #266 and #219 all fit that description.

**Comment by markoprljic** [comment] 2021-01-17 08:37
Perfect!

**Comment by freedumbs00** [comment] 2021-03-08 12:59
@GriffGreen   We currently only have one person with access to the hosted servers on Digital Ocean.  The problem is Discourse will not allow you to do anything through the app itself.  Everything has to be maintained through the Linux servers on Digital.  Only Kay has access to that.  If we want anything done in the future for anything backend it's completely reliant on that.

**Comment by Vyvy-vi** [comment] 2021-06-01 23:40
> Post count system, that not necessarily is post count, it could be read time too, but that's linked to the praise system.

Looking at the user stats, I think since Discourse automatically does the "posts read/read time", maybe we can use [discourse's API](https://docs.discourse.org/) to get access to those metrics? (and then link those metrics to praise, when they hit certain values?)

**Comment by Vyvy-vi** [comment] 2021-06-02 09:41
> Post count system, that not necessarily is post count, it could be read time too, but that's linked to the praise system.

![Screenshot 2021-06-02 at 3 03 08 PM](https://user-images.githubusercontent.com/62864373/120457253-ed232d80-c3b3-11eb-8f9f-bd3d165ee8f2.png)

(I rendered the above using discourse's API. Maybe we can set up the praise bot to automatically do this, and add a praise entry, or someone can run this script time to time and manually praise people in the server on a monthly basis(much like how we praise for twitter))

**Comment by Vyvy-vi** [comment] 2021-06-10 22:20
> Welcoming automated messages for new people / or different uses that having this system may bring.

I think the discobot gives a welcome tour of the forum. Perhaps we could tweak the bot or something of the sort, or make an application that welcomes people in a welcome thread, when they make an account on the forum?

**Comment by natenatesoo** [comment] 2021-08-06 17:30
Update: Closing this issue in favor of new.

**Closed by natenatesoo** 2021-08-06 17:30 UTC
Labels: Communications WG, Low, For Contributors
